添加收录与删除标准文档
dd-center/vdb pull request #11605
Opened 2022-09-17 15:26 UTC by Chen-Luan

tips：社团不收录毕业的

2022-09-18 22:22 UTC, simon300000 commented on docs/社团删除标准.md
> +- 由于成员离开导致所属VTB小于2人的。
我个人倾向是社团有成员就可以保留，这样可能会引起什么问题吗？

2022-09-18 22:28 UTC, simon300000 commented on docs/社团收录标准.md
> +不收录互助性质的社团企划。
这是指类似 SOW 这样的吗？

2022-09-18 23:22 UTC, wudifeixue commented on docs/VTB收录标准.md
> +请审核员为pr添加observe标签，并进行不少于15天的直播检查。
我去，这个有点太苛刻了吧，我觉得审核放宽点，有啥不行再删再改就是，谁有空盯着那么多人15天呢，最重要的是，错过的数据补不回来，多余的东西可以轻松的删掉

2022-09-18 23:23 UTC, wudifeixue commented on docs/VTB收录标准.md
> +收录的VTB不限平台，不限国家/地区。
我们只有b站吧？这里说的不太清楚感觉

2022-09-18 23:24 UTC, wudifeixue commented on docs/VTB收录标准.md
> +原则上审核员不应当批准自己提交的pr。
这个很难管，基本无效，匿名的pr可以提交然后自己批准

2022-09-18 23:26 UTC, wudifeixue reviewed
基本没啥问题，就是有些苛刻

2022-09-19 03:48 UTC, shugen002 commented on docs/社团收录标准.md
> +不收录互助性质的社团企划。
sow这种不具备排他性

2022-09-20 18:34 UTC, Radekyspec commented on docs/VTB收录标准.md
> +请审核员为pr添加observe标签，并进行不少于15天的直播检查。
> 我去，这个有点太苛刻了吧，我觉得审核放宽点，有啥不行再删再改就是，谁有空盯着那么多人15天呢，最重要的是，错过的数据补不回来，多余的东西可以轻松的删掉

我这边倒是可以检测开播然后去看一下，这个没问题

2022-09-20 18:54 UTC, Radekyspec commented on docs/VTB收录标准.md
> +这是主要的审核标准，满足以下所有要求即可认定达到收录标准。
我觉得视频和直播审核可以同步进行，满足一个就ok这样子

2022-09-20 18:54 UTC, Radekyspec commented on docs/VTB收录标准.md
> +- 若账号为录播号，只进入“审核投稿视频”流程，不进入“审核直播”流程，社团所属信息与视频对应的VTB所属信息一致。
emm还有那种专门发切片的账号，有一些发很多v的有一些只发一个v的，跟录播号一起算？

2022-09-20 18:54 UTC, Radekyspec commented on docs/VTB删除标准.md
> +- 删除历史视频导致不再符合收录条件，且3个月无动态的。
3个月似乎有点短。。？
我觉得3-6个月适合一点，有些人不经常发动态的。
但是也有说原则上不收长期不活跃的，好像也行（
还有一些只直播不发动态的也有。。或许有一次带l2d的直播也可以刷新这个期限。

2022-09-20 18:54 UTC, Radekyspec commented on docs/VTB收录标准.md
> +- 近期投稿视频/直播回放至少有50%出现L2D等虚拟形象（不含立绘）。
有模型的vrchat玩家，比较难看出来到底是不是当v运营的，审核的时候需要结合视频和直播特别关注一下

2022-09-20 18:54 UTC, Radekyspec commented on docs/VTB收录标准.md
> +- 15天内在直播中出现3次以上L2D等虚拟形象（不含立绘）。
或许”15天内有在虚拟区开播记录”也可以作为一个辅助证明

2022-09-20 19:56 UTC, wudifeixue commented on docs/VTB收录标准.md
> +请审核员为pr添加observe标签，并进行不少于15天的直播检查。
原来如此，这个现在不用担心了，我们把服务器优化到每天不足20%负载了，而且以后就算很多很多人，不经常开播也会自动降低他们的采集频率，现在数据多多益善

2022-09-20 19:57 UTC, wudifeixue commented on docs/VTB收录标准.md
> +这是主要的审核标准，满足以下所有要求即可认定达到收录标准。
比较认同这个

2022-09-21 06:11 UTC, shugen002 commented on docs/社团删除标准.md
> +- 由于成员离开导致所属VTB小于2人的。
如果严格按照社团收录标准的话，确实可以，毕竟搞成有资金关系这点就能筛掉大部分玩具了。

2022-09-21 06:21 UTC, shugen002 requested changes
能说的都被说了。

2022-09-21 07:30 UTC, wudifeixue commented on docs/VTB删除标准.md
> +- 删除历史视频导致不再符合收录条件，且3个月无动态的。
长期不活跃现在数据库会自动给放置到低频收录里，一天就扫一次，压力比以前小288倍，不用太担心清理了其实

2022-09-21 18:12 UTC, Radekyspec commented on docs/VTB收录标准.md
> +- 若账号为录播号，只进入“审核投稿视频”流程，不进入“审核直播”流程，社团所属信息与视频对应的VTB所属信息一致。
> 发多个V的不收录？我一会写进备注去

可以

2022-09-21 18:18 UTC, Radekyspec commented on docs/VTB收录标准.md
> +这是主要的审核标准，满足以下所有要求即可认定达到收录标准。
> > 我觉得视频和直播审核可以同步进行，满足一个就ok这样子
> 
> 这个是先检查一遍视频，视频不达标再审直播 也就是说一次性审核视频+一定时间审核直播，不存在同步的说法

了解了

2022-10-20 18:15 UTC, simon300000 commented
看起来已经稳定

2022-10-20 18:15 UTC, merged